<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Penginapan;

class PenginapanSeeder extends Seeder
{
    public function run(): void
    {
        // Data penginapan beserta fasilitas yang dimiliki (ID fasilitas)
        $data = [
            [
                'nama_penginapan'   => 'Golden Tulip Holland Resort',
                'alamat'            => 'Jl. Bukit Berbunga No. 59, Sidomulyo',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 1200000,
                'harga_max'         => 1500000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) mewah di Jl. Bukit Berbunga, Sidomulyo. Termasuk kriteria Mahal. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4], // Wi-Fi, Kolam Renang, Restoran, AC, TV
            ],
            [
                'nama_penginapan'   => 'Aston Inn Batu',
                'alamat'            => 'Jl. Abdul Gani Atas No. 42, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 500000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) modern dan nyaman di pusat Kota Batu, terletak di Jl. Abdul Gani Atas, Ngaglik. Termasuk kriteria Menengah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'The Onsen Hot Spring Resort',
                'alamat'            => 'Jl. Arumdalu Songgoriti, Songgokerto',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 1800000,
                'harga_max'         => 2200000,
                'deskripsi_singkat' => 'Hotel unik dengan pemandian air panas di Jl. Arumdalu Songgoriti, Songgokerto. Termasuk kriteria Mahal. Fasilitas: TV, Wi-Fi, Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'The Batu Hotel & Villas',
                'alamat'            => 'Jl. Sultan Agung No. 29, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 470000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Gabungan Hotel & Villa (Bintang 3) di pusat kota Jl. Sultan Agung, Sisir. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'Kontena Hotel',
                'alamat'            => 'Jl. Abdul Gani Atas, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 350000,
                'harga_max'         => 500000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dengan konsep unik di Jl. Abdul Gani Atas, Ngaglik. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang tersedia; tidak ada Restoran.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'éL Hotel Kartika Wijaya Batu',
                'alamat'            => 'Jl. Raya Oro-oro Ombo No. 2, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 500000,
                'harga_max'         => 650000,
                'deskripsi_singkat' => 'Hotel bersejarah (Bintang 4) di Jl. Raya Oro-oro Ombo, Sisir. Termasuk kriteria Menengah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Senyum World Hotel',
                'alamat'            => 'Jl. Ir. Soekarno No. 140, Mojorejo',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 500000,
                'harga_max'         => 750000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) besar dan strategis di Jl. Ir. Soekarno, Mojorejo. Termasuk kriteria Menengah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Amartahills Hotel and Resort',
                'alamat'            => 'Jl. Abdul Gani Atas, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 800000,
                'harga_max'         => 1100000,
                'deskripsi_singkat' => 'Hotel & Resort (Bintang 4) dengan pemandangan indah di Jl. Abdul Gani Atas, Ngaglik. Termasuk kriteria Menengah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Riverstone Hotel & Cottage',
                'alamat'            => 'Jl. Bukit Berbunga No. 100, Sidomulyo',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Hotel & Cottage (Bintang 3) yang tenang di Jl. Bukit Berbunga, Sidomulyo. Termasuk kriteria Murah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Pondok Jatim Park Hotel & Café',
                'alamat'            => 'Jl. Kartika No. 3, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 450000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dekat Jatim Park di Jl. Kartika, Sisir. Termasuk kriteria Murah. Fasilitas lengkap: TV, Wi-Fi, Kolam Renang, dan Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Apple Green Hotel Batu',
                'alamat'            => 'Jl. Abdul Gani Atas No. 8, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 350000,
                'harga_max'         => 500000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) di Jl. Abdul Gani Atas, Ngaglik. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi, Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'RedDoorz Near Alun Alun Batu 2',
                'alamat'            => 'Jl. Gondorejo No. 9, Oro-oro Ombo',
                'id_kategori'       => 1,
                'bintang'           => 2,
                'harga_min'         => 150000,
                'harga_max'         => 250000,
                'deskripsi_singkat' => 'Hotel Budget (Bintang 2) di Jl. Gondorejo, Oro-oro Ombo. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi tersedia.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Spencer Green Hotel Batu',
                'alamat'            => 'Jl. Raya Punten No. 100, Punten',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 300000,
                'harga_max'         => 450000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dengan suasana hijau di Jl. Raya Punten. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Ciptaningati Culture Hotel',
                'alamat'            => 'Jl. Abdul Gani Atas, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 450000,
                'harga_max'         => 550000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) bernuansa budaya di Jl. Abdul Gani Atas, Ngaglik. Termasuk kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran tersedia.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Samara Resort',
                'alamat'            => 'Jl. Indragiri No. 1, Songgokerto',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 650000,
                'deskripsi_singkat' => 'Resort (Bintang 3) yang nyaman di Jl. Indragiri, Songgokerto. Kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Hotel Batu Wonderland',
                'alamat'            => 'Jl. Imam Bonjol No. 9, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dengan taman air mini di Jl. Imam Bonjol, Sisir. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Royal Orchids Garden Hotel & Condominium',
                'alamat'            => 'Jl. Indragiri No. 4, Songgokerto',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 350000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Hotel & Condo (Bintang 4) di Jl. Indragiri, Songgokerto. Kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Kontjo Guesthouse',
                'alamat'            => 'Jl. Cempaka No. 8, Ngaglik',
                'id_kategori'       => 3,
                'bintang'           => null,
                'harga_min'         => 200000,
                'harga_max'         => 350000,
                'deskripsi_singkat' => 'Guesthouse minimalis di Jl. Cempaka, Ngaglik. Kriteria Murah. Fasilitas: TV, Wi-Fi.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Kusuma Agrowisata Hotel',
                'alamat'            => 'Jl. Abdul Gani Atas No. 9, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 600000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) di perkebunan apel Jl. Abdul Gani Atas, Ngaglik. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Mulyono',
                'alamat'            => 'Jl. Raya Punten No. 98, Punten',
                'id_kategori'       => 2,
                'bintang'           => 4,
                'harga_min'         => 900000,
                'harga_max'         => 1200000,
                'deskripsi_singkat' => 'Villa (Bintang 4) bernuansa alam di Jl. Raya Punten. Kriteria Mahal. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Batuque Town Villa',
                'alamat'            => 'Jl. Abdul Gani Atas, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Villa modern di Jl. Abdul Gani Atas, dekat Museum Angkut. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Della Scala',
                'alamat'            => 'Jl. Raya Oro-oro Ombo No. 5, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 4,
                'harga_min'         => 850000,
                'harga_max'         => 1100000,
                'deskripsi_singkat' => 'Villa (Bintang 4) dengan desain Eropa klasik di Jl. Oro-oro Ombo, Sisir. Kriteria Mahal. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Batu Paradise Resort Hotel',
                'alamat'            => 'Jl. Diponegoro No. 6, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 650000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) di Jl. Diponegoro, dekat Alun-alun Batu. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Villa Kencana Apel D5',
                'alamat'            => 'Jl. Oro-oro Ombo No. 10, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Villa nyaman dengan taman apel di Jl. Oro-oro Ombo. Kriteria Murah. Fasilitas: TV, Wi-Fi, Dapur.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Villa Araya',
                'alamat'            => 'Jl. Bukit Berbunga No. 22, Sidomulyo',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 700000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Villa (Bintang 3) luas dan tenang di kawasan Sidomulyo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Omah Koala Guesthouse',
                'alamat'            => 'Jl. Diponegoro No. 12, Sisir',
                'id_kategori'       => 3,
                'bintang'           => null,
                'harga_min'         => 250000,
                'harga_max'         => 400000,
                'deskripsi_singkat' => 'Guesthouse lucu dan nyaman di pusat kota Batu. Kriteria Murah. Fasilitas: Wi-Fi, TV.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Griya Sekar Kedaton',
                'alamat'            => 'Jl. Oro-oro Ombo No. 55, Sisir',
                'id_kategori'       => 3,
                'bintang'           => null,
                'harga_min'         => 300000,
                'harga_max'         => 450000,
                'deskripsi_singkat' => 'Guesthouse dengan nuansa tradisional Jawa di Jl. Oro-oro Ombo. Kriteria Murah. Fasilitas: TV, Wi-Fi.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Villa Singhasari',
                'alamat'            => 'Jl. Arumdalu No. 7, Songgokerto',
                'id_kategori'       => 2,
                'bintang'           => 4,
                'harga_min'         => 950000,
                'harga_max'         => 1300000,
                'deskripsi_singkat' => 'Villa (Bintang 4) eksklusif di Jl. Arumdalu, Songgokerto. Kriteria Mahal. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'De Wahyu Hotel & Convention',
                'alamat'            => 'Jl. Raya Oro-oro Ombo No. 11, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dengan fasilitas convention hall di Jl. Oro-oro Ombo. Kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Puncak Garuda',
                'alamat'            => 'Jl. Abdul Gani Bawah No. 14, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 600000,
                'harga_max'         => 850000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan panorama indah di Jl. Abdul Gani Bawah. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Omah Kayu Paralayang',
                'alamat'            => 'Gunung Banyak, Songgokerto',
                'id_kategori'       => 3,
                'bintang'           => null,
                'harga_min'         => 350000,
                'harga_max'         => 500000,
                'deskripsi_singkat' => 'Guesthouse unik di ketinggian Gunung Banyak. Kriteria Murah. Fasilitas: TV, Wi-Fi.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Villa Bima Shakti',
                'alamat'            => 'Jl. Oro-oro Ombo No. 60, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 750000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dekat BNS di Jl. Oro-oro Ombo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Hotel Gradia 2',
                'alamat'            => 'Jl. Ikhwan Hadi No. 47, Ngaglik',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) di Jl. Ikhwan Hadi, Ngaglik. Kriteria Murah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Kusuma Estate 12',
                'alamat'            => 'Jl. Abdul Gani Atas No. 25, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Villa (Bintang 3) modern di Kusuma Estate, Ngaglik. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Pinus Cemara',
                'alamat'            => 'Jl. Oro-oro Ombo No. 75, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 600000,
                'harga_max'         => 850000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan suasana alam di Oro-oro Ombo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Batu Love Garden Villa',
                'alamat'            => 'Jl. Ir. Soekarno No. 100, Beji',
                'id_kategori'       => 2,
                'bintang'           => 4,
                'harga_min'         => 850000,
                'harga_max'         => 1200000,
                'deskripsi_singkat' => 'Villa (Bintang 4) dekat Jatim Park 4. Kriteria Mahal. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Batu Highland Villa',
                'alamat'            => 'Jl. Raya Selecta No. 88, Tulungrejo',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 600000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan pemandangan pegunungan. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Purnama Hotel & Convention',
                'alamat'            => 'Jl. Raya Selecta No. 1, Punten',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 600000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) besar dengan fasilitas lengkap di Jl. Raya Selecta. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Dedaunan Villa',
                'alamat'            => 'Jl. Trunojoyo No. 2, Songgokerto',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 750000,
                'deskripsi_singkat' => 'Villa (Bintang 3) bernuansa alami di Jl. Trunojoyo, Songgokerto. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Cendana Villa Batu',
                'alamat'            => 'Jl. Oro-oro Ombo No. 88, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Villa (Bintang 3) di Jl. Oro-oro Ombo, dekat BNS. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Ubud Hotel & Cottages Batu',
                'alamat'            => 'Jl. Bendungan Sutami No. 18, Sisir',
                'id_kategori'       => 1,
                'bintang'           => 4,
                'harga_min'         => 650000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Hotel (Bintang 4) bernuansa Bali di pusat Kota Batu. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang, Restoran.',
                'id_fasilitas'      => [1, 2, 3, 4],
            ],
            [
                'nama_penginapan'   => 'Villa Panderman View',
                'alamat'            => 'Jl. Oro-oro Ombo No. 90, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan pemandangan Panderman di Oro-oro Ombo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Green Apple Villa',
                'alamat'            => 'Jl. Raya Punten No. 33, Punten',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 450000,
                'harga_max'         => 650000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan kebun apel di sekitar Punten. Kriteria Murah. Fasilitas: TV, Wi-Fi.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Hotel Surya Indah',
                'alamat'            => 'Jl. Raya Selecta No. 3, Tulungrejo',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 650000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) di kawasan wisata Selecta. Kriteria Murah. Fasilitas: TV, Wi-Fi, Restoran.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'Villa Kusuma Pinus',
                'alamat'            => 'Jl. Abdul Gani Atas No. 20, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dekat Kusuma Agrowisata. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Omah Yanti Guesthouse',
                'alamat'            => 'Jl. Diponegoro No. 25, Sisir',
                'id_kategori'       => 3,
                'bintang'           => null,
                'harga_min'         => 250000,
                'harga_max'         => 400000,
                'deskripsi_singkat' => 'Guesthouse bersih dan strategis di Jl. Diponegoro. Kriteria Murah. Fasilitas: Wi-Fi, TV.',
                'id_fasilitas'      => [1, 2],
            ],
            [
                'nama_penginapan'   => 'Villa Cendrawasih',
                'alamat'            => 'Jl. Raya Selecta No. 15, Tulungrejo',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan taman luas di Selecta. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Bukit Zaitun',
                'alamat'            => 'Jl. Raya Gunungsari No. 9, Gunungsari',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 700000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan pemandangan lembah di Gunungsari. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'De View Hotel Batu',
                'alamat'            => 'Jl. Bukit Berbunga No. 45, Sidomulyo',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 450000,
                'harga_max'         => 650000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) di area perbukitan Sidomulyo. Kriteria Murah. Fasilitas: TV, Wi-Fi, Restoran.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'Villa Panderman Estate',
                'alamat'            => 'Jl. Abdul Gani Atas No. 30, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 4,
                'harga_min'         => 800000,
                'harga_max'         => 1100000,
                'deskripsi_singkat' => 'Villa (Bintang 4) eksklusif di kawasan Panderman Estate. Kriteria Mahal. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Cemara Indah',
                'alamat'            => 'Jl. Raya Oro-oro Ombo No. 72, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 750000,
                'deskripsi_singkat' => 'Villa (Bintang 3) di Oro-oro Ombo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Hotel Grand Palem Batu',
                'alamat'            => 'Jl. Raya Punten No. 77, Punten',
                'id_kategori'       => 1,
                'bintang'           => 3,
                'harga_min'         => 400000,
                'harga_max'         => 600000,
                'deskripsi_singkat' => 'Hotel (Bintang 3) dengan suasana tropis di Punten. Kriteria Murah. Fasilitas: TV, Wi-Fi, Restoran.',
                'id_fasilitas'      => [1, 2, 4],
            ],
            [
                'nama_penginapan'   => 'Villa Damar Batu',
                'alamat'            => 'Jl. Arumdalu No. 11, Songgokerto',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 600000,
                'harga_max'         => 850000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan nuansa alami di Songgokerto. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Bamboo Forest',
                'alamat'            => 'Jl. Raya Oro-oro Ombo No. 95, Sisir',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 650000,
                'harga_max'         => 900000,
                'deskripsi_singkat' => 'Villa (Bintang 3) dengan tema bambu alami. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Family Batu',
                'alamat'            => 'Jl. Bukit Berbunga No. 10, Sidomulyo',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 500000,
                'harga_max'         => 750000,
                'deskripsi_singkat' => 'Villa (Bintang 3) cocok untuk keluarga di kawasan Sidomulyo. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ],
            [
                'nama_penginapan'   => 'Villa Kusuma Hills',
                'alamat'            => 'Jl. Abdul Gani Atas No. 40, Ngaglik',
                'id_kategori'       => 2,
                'bintang'           => 3,
                'harga_min'         => 550000,
                'harga_max'         => 800000,
                'deskripsi_singkat' => 'Villa (Bintang 3) di area Kusuma Hills, Ngaglik. Kriteria Menengah. Fasilitas: TV, Wi-Fi, Kolam Renang.',
                'id_fasilitas'      => [1, 2, 3],
            ]

        ];

        // Simpan penginapan dan relasi fasilitas
        foreach ($data as $item) {
            $penginapan = Penginapan::create([
                'nama_penginapan'   => $item['nama_penginapan'],
                'alamat'            => $item['alamat'],
                'id_kategori'       => $item['id_kategori'],
                'bintang'           => $item['bintang'],
                'harga_min'         => $item['harga_min'],
                'harga_max'         => $item['harga_max'],
                'deskripsi_singkat' => $item['deskripsi_singkat'],
            ]);

            $penginapan->fasilitas()->attach($item['id_fasilitas']);
        }
    }
}
